In [1]:
import pandas as pd

In [2]:
# Load in the data set.
file = 'Life_Expectancy.csv'
life_df = pd.read_csv(file)
life_df

,State,County,Census Tract Number,Life Expectancy,Life Expectancy Range,Life Expectancy Standard Error
0,Alabama,(blank),NaN,75.5,75.2-77.5,0.0328
1,Alabama,"Autauga County, AL",201.00,73.1,56.9-75.1,2.2348
2,Alabama,"Autauga County, AL",202.00,76.9,75.2-77.5,3.3453
3,Alabama,"Autauga County, AL",203.00,NaN,NaN,NaN
4,Alabama,"Autauga County, AL",204.00,75.4,75.2-77.5,1.0216
...,...,...,...,...,...,...
73116,Wyoming,"Washakie County, WY",2.00,80.1,79.6-81.6,2.6916
73117,Wyoming,"Washakie County, WY",3.01,79.9,79.6-81.6,2.8024
73118,Wyoming,"Washakie County, WY",3.02,81.8,81.7-97.5,2.0776
73119,Wyoming,"Weston County, WY",9511.00,79.0,77.6-79.5,1.0697
73120,Wyoming,"Weston County, WY",9513.00,78.6,77.6-79.5,1.6093

In [3]:
# Rename columns to match SQL database
life_expectancy_df = life_df.rename(columns = {'State':'state', 'County': 'county', 'Census Tract Number': 'census_tract_number', 'Life Expectancy':'life_expectancy', 'Life Expectancy Range': 'life_expectancy_range', 'Life Expectancy Standard Error': 'life_expectancy_standard_error'})
life_expectancy_df

,state,county,census_tract_number,life_expectancy,life_expectancy_range,life_expectancy_standard_error
0,Alabama,(blank),NaN,75.5,75.2-77.5,0.0328
1,Alabama,"Autauga County, AL",201.00,73.1,56.9-75.1,2.2348
2,Alabama,"Autauga County, AL",202.00,76.9,75.2-77.5,3.3453
3,Alabama,"Autauga County, AL",203.00,NaN,NaN,NaN
4,Alabama,"Autauga County, AL",204.00,75.4,75.2-77.5,1.0216
...,...,...,...,...,...,...
73116,Wyoming,"Washakie County, WY",2.00,80.1,79.6-81.6,2.6916
73117,Wyoming,"Washakie County, WY",3.01,79.9,79.6-81.6,2.8024
73118,Wyoming,"Washakie County, WY",3.02,81.8,81.7-97.5,2.0776
73119,Wyoming,"Weston County, WY",9511.00,79.0,77.6-79.5,1.0697
73120,Wyoming,"Weston County, WY",9513.00,78.6,77.6-79.5,1.6093

In [4]:
# Set state as index
life_expectancy_df.set_index('state', inplace=True)
life_expectancy_df

,county,census_tract_number,life_expectancy,life_expectancy_range,life_expectancy_standard_error
state,,,,,
Alabama,(blank),NaN,75.5,75.2-77.5,0.0328
Alabama,"Autauga County, AL",201.00,73.1,56.9-75.1,2.2348
Alabama,"Autauga County, AL",202.00,76.9,75.2-77.5,3.3453
Alabama,"Autauga County, AL",203.00,NaN,NaN,NaN
Alabama,"Autauga County, AL",204.00,75.4,75.2-77.5,1.0216
...,...,...,...,...,...
Wyoming,"Washakie County, WY",2.00,80.1,79.6-81.6,2.6916
Wyoming,"Washakie County, WY",3.01,79.9,79.6-81.6,2.8024
Wyoming,"Washakie County, WY",3.02,81.8,81.7-97.5,2.0776
Wyoming,"Weston County, WY",9511.00,79.0,77.6-79.5,1.0697
Wyoming,"Weston County, WY",9513.00,78.6,77.6-79.5,1.6093

In [8]:
#Drop null values
life_expectancy_df.dropna(axis=0, how='any', inplace=True)
life_expectancy_df

,county,census_tract_number,life_expectancy,life_expectancy_range,life_expectancy_standard_error
state,,,,,
Alabama,"Autauga County, AL",201.00,73.1,56.9-75.1,2.2348
Alabama,"Autauga County, AL",202.00,76.9,75.2-77.5,3.3453
Alabama,"Autauga County, AL",204.00,75.4,75.2-77.5,1.0216
Alabama,"Autauga County, AL",205.00,79.4,77.6-79.5,1.1768
Alabama,"Autauga County, AL",206.00,73.1,56.9-75.1,1.5519
...,...,...,...,...,...
Wyoming,"Washakie County, WY",2.00,80.1,79.6-81.6,2.6916
Wyoming,"Washakie County, WY",3.01,79.9,79.6-81.6,2.8024
Wyoming,"Washakie County, WY",3.02,81.8,81.7-97.5,2.0776
Wyoming,"Weston County, WY",9511.00,79.0,77.6-79.5,1.0697
Wyoming,"Weston County, WY",9513.00,78.6,77.6-79.5,1.6093

In [9]:
# Export to a CSV
life_expectancy_df.to_csv('life_expectancy_clean_2.csv', header=False)